<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <ItemGroup>
    <ProjectReference Include="..\OrderApi\OrderApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Valkey" Version="13.4.3" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Dapr" Version="13.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>7210906e-f3a4-4901-a980-c8cf2d902c9e</UserSecretsId>
  </PropertyGroup>

</Project>
